# Generated by Django 4.0.5 on 2022-07-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_page', '0002_tag_table_review_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_table',
            name='tags',
            field=models.ManyToManyField(blank=True, to='projects_page.tag_table'),
        ),
        migrations.AddField(
            model_name='project_table',
            name='vote_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='project_table',
            name='vote_ratio',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
